# Final 58-column schema (locked)

SUMMARY_COLUMNS = [
    "Track",
    "Race_Date",
    "Race_No",
    "Box",
    "Dog_Name",
    "Tab_No",
    "FF_Form",
    "BP",
    "A/S",
    "WT (kg)",
    "Trainer",
    "Sire",
    "Dam",
    "Owner",
    "Career_W-P-S",
    "Prize_Money",
    "RTC",
    "DLR",
    "DLW",
    "Car_PM/s (G1)",
    "12m_PM/s (G2)",
    "API (G3)",
    "RTC/km",
    "Trainer_Win_%",
    "Trainer_Place_%",
    "Raced_Dist_W-P-S",
    "Crs_W-P-S",
    "Dist_W-P-S",
    "FU_W-P-S",
    "2U_W-P-S",
    "DOD",
    "Avg_Speed_km/h",
    "Min_Speed_km/h",
    "Max_Speed_km/h",
    "Hist_Count",
    "Hist_Date",
    "Hist_Track",
    "Hist_Distance",
    "Hist_Finish_Pos",
    "Hist_Margin_L",
    "Hist_Race_Time",
    "Hist_Sec_Time",
    "Hist_Sec_Time_Adj",
    "Hist_Speed_km/h",
    "Hist_SOT",
    "Hist_RST",
    "Hist_BP",
    "Hist_Odds",
    "Hist_API",
    "Hist_Prize_Won",
    "Hist_Winner",
    "Hist_2nd_Place",
    "Hist_3rd_Place",
    "Hist_Settled_Turn",
    "Hist_Ongoing_Winners",
    "Hist_Track_Direction",
    "Data_Source_File",
    "Parse_Timestamp",
]

DEDUPE_KEYS = (
    "Track",
    "Race_Date",
    "Race_No",
    "Box",
    "Dog_Name",
)

# Legacy columns preserved temporarily to avoid breaking pipeline.
# These come directly from your ZIP (greyhound-docx-extractor-v3-main/src/columns.py)

LEGACY_COLUMNS = [
    "Meeting_Date",
    "Meeting_Time",
    "Weather",
    "Track_Condition",
    "Rail_Position",
    "Race_Name",
    "Race_Class",
    "Distance",
    "Prize",
    "Scratched",
    "Dog",
    "Sex",
    "Age",
    "Color",
    "Weight",
    "Trainer_Name",
    "Owner_Name",
    "Breeding",
    "TAB",
    "Form",
    "Career",
    "Wins",
    "Places",
    "Starts",
    "DLR_Old",
    "DLW_Old",
    "RTN",
    "Trainer_Stats",
    "Sectional_Time",
    "Run_Time",
    "Margin",
    "SOT",
    "RST",
    "Box_Draw",
    "Odds",
    "API_Old",
    "Prize_Won",
    "Winner",
    "Second",
    "Third",
    "Settled",
    "Ongoing_Winners",
    "Track_Dir",
    "Notes",
    "Race_Grade",
    "Meeting_ID",
    "Raw_Text",
]

# Full schema used internally = final columns + legacy columns
ALL_COLUMNS = SUMMARY_COLUMNS + LEGACY_COLUMNS

# History row schema (stable)
HISTORY_COLUMNS = [
    "Track",
    "Race_Date",
    "Race_No",
    "Box",
    "Dog_Name",
    "Hist_Date",
    "Hist_Track",
    "Hist_Distance",
    "Hist_Finish_Pos",
    "Hist_Margin_L",
    "Hist_Race_Time",
    "Hist_Sec_Time",
    "Hist_Sec_Time_Adj",
    "Hist_Speed_km/h",
    "Hist_SOT",
    "Hist_RST",
    "Hist_BP",
    "Hist_Odds",
    "Hist_API",
    "Hist_Prize_Won",
    "Hist_Winner",
    "Hist_2nd_Place",
    "Hist_3rd_Place",
    "Hist_Settled_Turn",
    "Hist_Ongoing_Winners",
    "Hist_Track_Direction",
    "Data_Source_File",
]
